spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.105/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
wechat:
  mpAppId: wxf877e195a0cf0034
  mpAppSecret: 8c3fa673cc3b89aeeea463e73b5a161a
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
