spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sh_951753.
    url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true